// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Todos      string
	TodosUsers string
	Users      string
}{
	Todos:      "todos",
	TodosUsers: "todos_users",
	Users:      "users",
}
